"""phase 3-4: customers, environments, services, repositories, deployments, tickets, ticket_events

Revision ID: 6e612ab472a9
Revises: 5b03c1f554fb
Create Date: 2026-09-30 20:29:09.815968
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e612ab472a9'
down_revision: Union[str, None] = '5b03c1f554fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('external_ref', sa.String(length=200), nullable=True),
    sa.Column('tier', sa.Enum('FREE', 'STANDARD', 'ENTERPRISE', name='customer_tier'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_customers_id_org')
    )
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.create_table('customer_environments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id', 'organization_id'], ['customers.id', 'customers.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'name', name='uq_environment_customer_name'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_environments_id_org')
    )
    op.create_index(op.f('ix_customer_environments_customer_id'), 'customer_environments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_environments_organization_id'), 'customer_environments', ['organization_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ticket_priority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'ROOT_CAUSE_FOUND', 'FIX_PROPOSED', 'VALIDATING', 'RESOLVED', 'ESCALATED', name='ticket_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id', 'organization_id'], ['customers.id', 'customers.organization_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_tickets_id_org')
    )
    op.create_index(op.f('ix_tickets_customer_id'), 'tickets', ['customer_id'], unique=False)
    op.create_index(op.f('ix_tickets_organization_id'), 'tickets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tickets_status'), 'tickets', ['status'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('owner_team', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id', 'organization_id'], ['customer_environments.id', 'customer_environments.organization_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment_id', 'name', name='uq_service_environment_name'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_services_id_org')
    )
    op.create_index(op.f('ix_services_environment_id'), 'services', ['environment_id'], unique=False)
    op.create_index(op.f('ix_services_organization_id'), 'services', ['organization_id'], unique=False)
    op.create_table('ticket_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('CREATED', 'FIELD_CHANGED', 'STATUS_CHANGED', 'COMMENT', name='ticket_event_type'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id', 'organization_id'], ['tickets.id', 'tickets.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_events_organization_id'), 'ticket_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ticket_events_ticket_id'), 'ticket_events', ['ticket_id'], unique=False)
    op.create_table('code_repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('LOCAL', 'GITHUB', 'GITLAB', name='repository_provider'), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('default_branch', sa.String(length=100), server_default='main', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id', 'organization_id'], ['services.id', 'services.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_code_repositories_id_org')
    )
    op.create_index(op.f('ix_code_repositories_organization_id'), 'code_repositories', ['organization_id'], unique=False)
    op.create_index(op.f('ix_code_repositories_service_id'), 'code_repositories', ['service_id'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUCCESS', 'FAILED', 'ROLLED_BACK', name='deployment_status'), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id', 'organization_id'], ['services.id', 'services.organization_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_deployments_id_org')
    )
    op.create_index(op.f('ix_deployments_organization_id'), 'deployments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_deployments_service_id'), 'deployments', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployments_service_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_organization_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_code_repositories_service_id'), table_name='code_repositories')
    op.drop_index(op.f('ix_code_repositories_organization_id'), table_name='code_repositories')
    op.drop_table('code_repositories')
    op.drop_index(op.f('ix_ticket_events_ticket_id'), table_name='ticket_events')
    op.drop_index(op.f('ix_ticket_events_organization_id'), table_name='ticket_events')
    op.drop_table('ticket_events')
    op.drop_index(op.f('ix_services_organization_id'), table_name='services')
    op.drop_index(op.f('ix_services_environment_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_tickets_status'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_organization_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_customer_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_customer_environments_organization_id'), table_name='customer_environments')
    op.drop_index(op.f('ix_customer_environments_customer_id'), table_name='customer_environments')
    op.drop_table('customer_environments')
    op.drop_index(op.f('ix_customers_organization_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###

    # Not auto generated: dropping a table doesn't drop the native Postgres
    # enum type(s) it used, which then breaks a later `upgrade` with
    # "type already exists" — see the first migration's downgrade() for
    # where this was originally caught via an actual upgrade/downgrade/
    # upgrade round-trip against a real database.
    sa.Enum(name='deployment_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='repository_provider').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='ticket_event_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='ticket_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='ticket_priority').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='customer_tier').drop(op.get_bind(), checkfirst=True)
