"""phase 6: integrations table

Revision ID: d5ad3d246dd3
Revises: 6e612ab472a9
Create Date: 2026-10-01 01:00:51.727642
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5ad3d246dd3'
down_revision: Union[str, None] = '6e612ab472a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('CODE_HOST', 'LOG_SOURCE', 'DATA_SOURCE', 'DEPLOYMENT_SOURCE', 'SUPPORT_SOURCE', name='integration_kind'), nullable=False),
    sa.Column('provider', sa.Enum('LOCAL', name='integration_provider'), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('secret_ref', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'organization_id', name='uq_integrations_id_org')
    )
    op.create_index(op.f('ix_integrations_organization_id'), 'integrations', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integrations_organization_id'), table_name='integrations')
    op.drop_table('integrations')
    # ### end Alembic commands ###
    # Autogenerate never drops native Postgres enum types (see the Phase
    # 3/4 migration for the same fix) — without this, a second `upgrade`
    # after this `downgrade` fails with "type already exists".
    sa.Enum(name='integration_kind').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='integration_provider').drop(op.get_bind(), checkfirst=True)
